#
# https://travis-ci.org/MichelleLu1995/PLT/
#

sudo: required
language: python
python: "2.7_with_system_site_packages"
env: "OCAML_VERSION=4.01.0 OPAM_VERSION=1.2.0"
install:
    - sudo pip install -r requirements.txt
    - sudo apt-get install -qq m4 llvm software-properties-common
    - sudo add-apt-repository --yes ppa:avsm/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y ocaml ocaml-native-compilers menhir opam
    - opam init -a
    - eval `opam config env`
    - opam install -y depext
    - opam depext llvm.3.4
    - opam install -y llvm.3.4 ocamlfind ocamlbuild
script: make test

