# 
# JSTEM: MAIN MAKEFILE
#  

OCAMLC = ocamlc
OCAMLLEX = ocamllex
OCAMLYACC = ocamlyacc
OBJS = parser.cmo scanner.cmo ast.cmo 


build: $(OBJS)
	$(OCAMLC) -g -o JSTEM $(OBJS)

scanner.ml: scanner.mll
	$(OCAMLLEX) scanner.mll

parser.ml parser.mli: parser.mly
	$(OCAMLYACC) parser.mly

%.cmo: %.ml
	$(OCAMLC) -c $<

%.cmi: %.mli
	$(OCAMLC) -c $<


test: build
	cd tests; make


.PHONY: clean
clean:
	cd tests; make clean
	rm -f JSTEM scanner.ml parser.ml parser.mli *.cmo *.cmi 

# Generated by ocamldep *.ml *.mli
parser.cmo: ast.cmo parser.cmi 
parser.cmx: ast.cmx parser.cmi 
scanner.cmo: parser.cmi 
scanner.cmx: parser.cmx 